### ISSUE TITLE
one of major problems

### ISSUE THREAD

**Issue by razzaghi** [WellCommerce/WellCommerce#100]
one of major problem is the data for other language doesn't save

For example you add another language and go to product edit mode
and enter new value for other language when u click save and finish or save and continue it doesn't save other language data and doesn't show any error message.

**Comment by razzaghi** [comment]
i find data save but replace in en values and lose before data
i check in database

**Comment by adampiotrowski** [comment]
Resolved by disabling the locale filter in Doctrine.
