### ISSUE TITLE
Something wrong on the backend product list use symfony3.1.3

### ISSUE THREAD

**Issue by benyang2015** [WellCommerce/WellCommerce#105]
The server has responded with an invalid data.
An exception occurred while executing 'SELECT p0_.id AS id_0, p1_.name AS name_1, p0_.sku AS sku_2, p0_.weight AS weight_3, p0_.sell_price_gross_amount AS sell_price_gross_amount_4, p0_.stock AS stock_5, s2_.id AS id_6, t3_.value AS value_7, GROUP_CONCAT(DISTINCT c4_.name ORDER BY c4_.name ASC SEPARATOR ', ') AS sclr_8 FROM product p0_ LEFT JOIN product_translation p1_ ON p0_.id = p1_.translatable_id AND (p1_.locale = 'en') LEFT JOIN category_product c6_ ON p0_.id = c6_.product_id LEFT JOIN category c5_ ON c5_.id = c6_.category_id LEFT JOIN producer p7_ ON p0_.producer_id = p7_.id LEFT JOIN tax t3_ ON p0_.sell_tax_id = t3_.id LEFT JOIN category_translation c4_ ON c5_.id = c4_.translatable_id AND (c4_.locale = 'en') LEFT JOIN producer_translation p8_ ON p7_.id = p8_.translatable_id AND (p8_.locale = 'en') LEFT JOIN product_photo p9_ ON p0_.id = p9_.product_id AND (p9_.main_photo = ?) LEFT JOIN media m10_ ON p9_.photo_id = m10_.id LEFT JOIN product_distinction p11_ ON p0_.id = p11_.product_id AND (p11_.product_status_id = ?) LEFT JOIN shop_product s12_ ON p0_.id = s12_.product_id LEFT JOIN shop s2_ ON s2_.id = s12_.shop_id GROUP BY p0_.id ORDER BY p0_.id DESC LIMIT 50 OFFSET 0' with params [1, 0]: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'wellcommerce.p1_.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by adampiotrowski** [comment]
It'a Doctrine & MySQL related problem, see https://github.com/doctrine/doctrine2/issues/5622

Which version of MySQL are you using @benyang2015 ?

**Comment by benyang2015** [comment]
mysql5.7

**Comment by adampiotrowski** [comment]
@benyang2015 Sorry for late reply. It's a mysql strict-mode related problem. Could you please disable the only_full_group_by in mysql settings? Here's one solution

http://craftcms.stackexchange.com/a/12106
