### ISSUE TITLE
Generate new entity in custom bundle

### ISSUE THREAD

**Issue by argoitz** [WellCommerce/WellCommerce#106]
Hi, i'm triing to create a new entity for a custom table in DB but i have this error when i try to generate entities:

`Call to a member function implementsInterface() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function implementsInterface() on null at /var/www/html/wellcommerce/src/WellCommerce/Bundle/RoutingBundle/EventListener/RoutableSubscriber.php:49)"}
`

I do these steps:
1.- Generate new bundle (BannerBundle) with this command: php app/console generate:bundle
2.- Generate new entity with this command: app/console doctrine:generate:entity
3.- I try to update the schema like this ( php app/console doctrine:schema:update --force
) but console says: Nothing to update - your database is already in sync with the current entity metadata.

4.- I try to generate entities to solve step 3: app/console doctrine:generate:entities BannerBundle

I don't know what I'm doing wrong, but I need to create a new Bundle with entity associated with DB table.

Thank you.

**Comment by adampiotrowski** [comment]
@argoitz Did you removed the app/cache/dev prior to running those commands?

Please use doctrine:migrations:diff and doctrine:migrations:migrate instead of doctrine:schema:update. What's the output?

**Comment by argoitz** [comment]
I remove cache and execute these commands and this is the result:

> Doctrine:migration:diff -> No changes detected in your mapping information.
> Doctrine:migration:migrate -> Migrating up to 0 from 0
>                                                  [Doctrine\DBAL\Migrations\MigrationException]
>                                                  Could not find any migrations to execute.

**Comment by adampiotrowski** [comment]
@argoitz Looks like that Doctrine is not aware of new entities or whole bundle. Few questions:

- does your bundle extends AbstractWellCommerceBundle?
- does the bundle extension (DependencyInjection folder) extends AbstractExtension?
- do you have properly configured mapping files and they're available in Resources/config/doctrine folder?

We have some "magic" underneath so the services, mappings are registered automatically during container compilation process. 

Pls check also if your new bundle is visible in app/cache/dev/bundles.php file. 

Additionaly what is the project structure, in which src sub-directory is your bundle?

I'd love to have a look at this, do you have any possibility to show me the codebase of your bundle?

**Comment by argoitz** [comment]
Hi @adampiotrowski and thank you for answering.

I have this structure of my custom bundle:

> src/Custom/BannerBundle/Controller/BannerController.php
> src/Custom/BannerBundle/Entity/BannerEntity.php
> src/Custom/BannerBundle/Repository/BannerEntityRepository.php
> src/Custom/BannerBundle/Resources/config/services.yml
> src/Custom/BannerBundle/Resources/views/Default/index.html.twig
> src/Custom/BannerBundle/Tests/Controller/BannerControllerControllerTest.php
> src/Custom/BannerBundle/Tests/Controller/BannerControllerTest.php
> src/Custom/BannerBundle/CustomBannerBundle.php



Then, I will try to answer your questions:
1.- My bundle (src/Custom/BannerBundle/CustomBannerBundle.php) extends "Bundle", i try to extend "AbstractWellCommerceBundle" but i get this error:
`ClassNotFoundException in CustomBannerBundle.php line 7:
Attempted to load class "AbstractWellCommerceBundle" from namespace "Custom\BannerBundle".`

2.- Probably i have not this Dependency injection folder or i don't know where can i find it.

3.- I create Bundle and Entity with Symfony's app/console and this commands does not create this Doctrine folder.

# 
src/Custom/BannerBundle/CustomBannerBundle.php
`<?php

namespace Custom\BannerBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class CustomBannerBundle extends Bundle
{
}
`


# 
src/Custom/BannerBundle/Controller/BannerController.php
`<?php

namespace Custom\BannerBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class BannerController extends Controller
{
	/**
     * @Route("/")
     */
	public function indexAction()
    {
        return $this->render('CustomBannerBundle:Default:index.html.twig');
    }
}
`


# src/Custom/BannerBundle/Entity/BannerEntity.php

`<?php

namespace Custom\BannerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * BannerEntity
 *
 * @ORM\Table(name="banner_entity")
 * @ORM\Entity(repositoryClass="Custom\BannerBundle\Repository\BannerEntityRepository")
 */
class BannerEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="foto", type="string", length=255, nullable=true)
     */
    private $foto;

    /**
     * @var string
     *
     * @ORM\Column(name="texto", type="string", length=255, nullable=true)
     */
    private $texto;

    /**
     * @var string
     *
     * @ORM\Column(name="link", type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @var int
     *
     * @ORM\Column(name="orden", type="integer")
     */
    private $orden;

    /**
     * @var bool
     *
     * @ORM\Column(name="int_ext", type="boolean")
     */
    private $intExt;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set foto
     *
     * @param string $foto
     *
     * @return BannerEntity
     */
    public function setFoto($foto)
    {
        $this->foto = $foto;

        return $this;
    }

    /**
     * Get foto
     *
     * @return string
     */
    public function getFoto()
    {
        return $this->foto;
    }

    /**
     * Set texto
     *
     * @param string $texto
     *
     * @return BannerEntity
     */
    public function setTexto($texto)
    {
        $this->texto = $texto;

        return $this;
    }

    /**
     * Get texto
     *
     * @return string
     */
    public function getTexto()
    {
        return $this->texto;
    }

    /**
     * Set link
     *
     * @param string $link
     *
     * @return BannerEntity
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Get link
     *
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Set orden
     *
     * @param integer $orden
     *
     * @return BannerEntity
     */
    public function setOrden($orden)
    {
        $this->orden = $orden;

        return $this;
    }

    /**
     * Get orden
     *
     * @return int
     */
    public function getOrden()
    {
        return $this->orden;
    }

    /**
     * Set intExt
     *
     * @param boolean $intExt
     *
     * @return BannerEntity
     */
    public function setIntExt($intExt)
    {
        $this->intExt = $intExt;

        return $this;
    }

    /**
     * Get intExt
     *
     * @return bool
     */
    public function getIntExt()
    {
        return $this->intExt;
    }
}

`


This is generated file's code. 
Probably I will understand better how to create a new bundle with custom entity and how to generate this new table in DB if you tell me the steps for that.

Thank you so much for your help.

**Comment by argoitz** [comment]
Hi @adampiotrowski Im triing to generate new user from admin panel and im getting this error:
`Call to a member function getId() on null
src/WellCommerce/Bundle/RoutingBundle/Generator/AbstractRouteGenerator.php at line 65`

In the demo of wellcomerce is working fine, I don't know if I install correctly the wellcommerce because we have a lot of errors in the panerl.
We install with this guide: https://www.virtual-server.org/blog/install-wellcommerce-on-an-ubuntu-vps/
We have installed master repository and I think you have a development version in the demo.
¿How can we update the code to the development version of the repository?

Thank you so much.

**Comment by adampiotrowski** [comment]
@argoitz Now i see.

Instead of using a generator i'd use one of our "pluggable" bundles (they'll be installed through the app marketplace in near future). Take look at ReviewBundle or CouponBundle. It's not too hard to duplicate those bundles only by copying and replacing the names/namespaces.

DX is very important for use so i'll prepare our own bundle generator. At this moment i can only give you some hints which should point you into right direction:

1). ClassNotFoundException is triggered because you didn't put a proper use statement in your class ie. it should look like

```
<?php

namespace Custom\BannerBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;
use WellCommerce\Bundle\CoreBundle\HttpKernel\AbstractWellCommerceBundle;

class CustomBannerBundle extends AbstractWellCommerceBundle
{
}
```

then it'll auto-register the services found in your bundle. 

2). simply copy the folder & tune an existing classes ie. https://github.com/WellCommerce/WellCommerce/tree/development/src/WellCommerce/Bundle/ReviewBundle/DependencyInjection

You must follow the conventions so there should be a
```
Configuration.php
and
CustomBannerExtension.php 
```

Both must have proper namespaces and extends. Every extension must extend base AbstractExtension. Take a look at https://github.com/WellCommerce/WellCommerce/blob/development/src/WellCommerce/Bundle/ReviewBundle/DependencyInjection/WellCommerceReviewExtension.php

3). yes, because the generator uses ORM annotations and we're using YAML configuration. Annotations aren't supported. You should have the mapping files in Resources/config/doctrine directory

https://github.com/WellCommerce/WellCommerce/tree/development/src/WellCommerce/Bundle/ReviewBundle/Resources/config/doctrine

4). yes, because your bundle doesn't extend our base bundle, as in point 1. 

5). 

```
- The requested package react/child-process 0.5.*@dev exists as react/child-process[0.3.x-dev, dev-master, dev-windows-test-compat, v0.3.0, v0.4.0, v0.4.1] but these are rejected by your constraint.
```

Please update your repository (you're using Git clone right?) or manually change

```
"react/child-process": "0.5.*@dev",

to 

"react/child-process": "dev-master",
```
in your composer.json and run composer update commands ie. php composer.phar update

BTW. we aren't using Symfony forms so using a generated bundle will lead to many other problems, missing forms, factories, templates. As i mentioned It'll be far easier to copy&replace one of our existing bundles.

**Comment by argoitz** [comment]
Hi @adampiotrowski, thank you for answering.
I try to create a new bundle with your instructions.

I'm trying to install wellcommerce stable version with this command, not with git clone: 
` php composer.phar create-project wellcommerce/wellcommerce -s stable wellcommerce_stable/ `

How can i update my repository in  this case? 

Thank you, you are helping me a lot.

**Comment by argoitz** [comment]
Hi @adampiotrowski, don't worry for the bugs I can post a bug issue later. 
I need to create a new bundle with custom entity and generate a database table with it.
I want to create this bundle to customize landing page's banners and i need to create a custom entity with (photo, link and a simple text).  

I copy ReviewBundle and rename it to BannerBundle, change controller and entity namespace,  but there are a lot of files inside this folder. I don't know if i have to rename all the files or if I can do it renaming the controller and entity.

Can you guide me please?

Thank you so much.

**Comment by adampiotrowski** [comment]
@argoitz Sure, I'll help. We're a little busy right now, there're ongoing preparations for the release next week. Tomorrow evening I'll give you detailed instructions how to make a custom bundle.

**Comment by argoitz** [comment]
Thank you @adampiotrowski, I'm waiting for it.

**Comment by adampiotrowski** [comment]
@argoitz I'll take a little bit longer than I though ;). Creating a whole new bundle from scratch requires also that you prepare the datasets, datagrids, admin controllers, factories etc. It's a complex process and i'm forced now to write a extensive tutorial on our blog. 

It'll be far easier to start with PageBundle which has some CMS options. Here're the steps. 

**1. preparation**

Duplicate all files inside 

`src/WellCommerce/Bundle/PageBundle`

to 

`src/Argoitz/Bundle/CustomBannerBundle` 

directory 

**2. find & replace all occurencies of**

`namespace WellCommerce\Bundle\PageBundle`

to 

`namespace Argoitz\Bundle\CustomBannerBundle`

inside src/Argoitz/Bundle/CustomBannerBundle directory

**3. remove unnecessary directories & files**

DataFixtures directory
Tests - you should write own for this bundle
Storage
Twig
Resources/config/serialization

Of course you'll be forced to review the services.yml file in Resources folder and remove references to storage and twig extension.

**4. rename the files**

All files containing the "Page*" part should be renamed so you follow the PSR ie.

rename WellCommercePageExtension.php to ArgoitzCustomBannerExtension.php
rename WellCommercePageBundle.php to ArgoitzCustomBannerBundle.php
rename PageController.php to CustomBannerController.php
rename PageDataSet.php to CustomBannerDataSet.php 
rename PageFormBuilder.php to CustomBannerFormBuilder.php

etc.

**4. change the entities**

We don't use annotation mapping but you must fine-tune the entities. Change the properties and getter/setter methods so they reflect required structure. 

ORM mapping is stored in Resources/config/doctrine directory and you must put there the files needed by your entities.

Follow the instructions here: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html

and here: http://brentertainment.com/other/docs/book/doctrine/orm.html

**5. forms, datasets, datagrids**

We're using a CRUD-like mechanism so if you follow the conventions it shouldn't be hard to change those classes. It's mainly about changing used property names.

**5. factory, repository, manager**

Repository should work without any changes but look at your ORM mapping files and repositoryClass option. 

Factory should be changed to reflect new properties used in your entity. 

Manager contains no logic, should work without any changes.

**6. tune the ORM validation configuration**

Look at Resources/config/validation directory. Put there your XML configuration files.

Here's the Symfony documentation: http://symfony.com/doc/current/validation.html

**7. change the admin templates**

They're stored in Resources/views directory. You should also rename the sub-directories and files. 

**8. review the configs**

It's mostly about changing the configuration in config.yml and services.yml for your new bundle.

**9. register and boot the bundle**

You don't need to change the AppKernel.php file. 

- add in app/config/wellcommerce.yml additional import

`- { resource: "@ArgoitzCustomBanner/Resources/config/config.yml" }`

- add routing definitions in app/config/routing.yml

argoitz_custom_banner:
`    resource: "@ArgoitzCustomBanner/Resources/config/routing.yml"`

After clearing the cache (ie. by removing app/cache directory) the bundle will be auto-registered. 


Try to complete the steps and we'll get further with more advanced topics.

**Comment by argoitz** [comment]
Thank you @adampiotrowski for your time, but i can't generate a new bundle. I get this error all the time: Class \Custom\Bundle\BannerBundle\CustomBannerBundle does not exist
I create a bundle in src/Custom/Bundle/BannerBundle.

Thank you for all.

**Comment by argoitz** [comment]
Hi @adampiotrowski, you will make a bundle, easy to duplicate in the next update of wellcommerce?
I'm getting the same error and i don't know what I'm doing wrong.

Thank you.

**Comment by argoitz** [comment]
Hi @adampiotrowski, finally i create a new bundle in Wellcommerce/Bundles/BannerBundle directory.  Now i have one error when i try to add a new banner and I ask you for help if it is possible.

I have two tables:

**banner**

- id (integer, primary, auto_increment)
- foto(varchar 255)
- texto(varchar 255)
- link(varchar 255)
- orden(integer )
- int_ext(boolean)

**banner_translation**

- id(integer, primary, auto increment)
- name (varchar 255)
- content(varchar 255)
- meta(varchar 255)
- translatable_id (integer)
- local(varchar 50)


And here the error when I click on add button:
> DataSet column "name" not found

Do you know how can I solve this error?


Thank you

**Comment by argoitz** [comment]
Hi @adampiotrowski,
Finally, I create a new bundle and it works fine for list insert and edit. I want to ask you for two questions:

1.- I have an error when i try to delete one and I don't know how to solve it. The error shows in the header of admin panel with red background.
This is the error:

> #0 /var/www/html/wellcommerce_git/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver-&gt;convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))

> #1 /var/www/html/wellcommerce_git/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT t0.name ...', Array)

> #2 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(1808): Doctrine\DBAL\Connection-&gt;executeQuery('SELECT t0.name ...', Array, Array)
> 
> #3 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(1747): Doctrine\ORM\Persisters\Entity\BasicEntityPersister-&gt;getOneToManyStatement(Array, Object(WellCommerce\Bundle\BannerBundle\Entity\Banner))
> 
> #4 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2835): Doctrine\ORM\Persisters\Entity\BasicEntityPersister-&gt;loadOneToManyCollection(Array, Object(WellCommerce\Bundle\BannerBundle\Entity\Banner), Object(Doctrine\ORM\PersistentCollection))
> 
> #5 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php(697): Doctrine\ORM\UnitOfWork-&gt;loadCollection(Object(Doctrine\ORM\PersistentCollection))
> 
> #6 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php(214): Doctrine\ORM\PersistentCollection-&gt;doInitialize()
> 
> #7 /var/www/html/wellcommerce_git/vendor/doctrine/collections/lib/Doctrine/Common/Collections/AbstractLazyCollection.php(274): Doctrine\ORM\PersistentCollection-&gt;initialize()
> 
> #8 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2280): Doctrine\Common\Collections\AbstractLazyCollection-&gt;getIterator()
> 
> #9 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1745): Doctrine\ORM\UnitOfWork-&gt;cascadeRemove(Object(WellCommerce\Bundle\BannerBundle\Entity\Banner), Array)
> 
> #10 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1716): Doctrine\ORM\UnitOfWork-&gt;doRemove(Object(WellCommerce\Bundle\BannerBundle\Entity\Banner), Array)
> 
> #11 /var/www/html/wellcommerce_git/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(602): Doctrine\ORM\UnitOfWork-&gt;remove(Object(WellCommerce\Bundle\BannerBundle\Entity\Banner))
> 
> #12 /var/www/html/wellcommerce_git/app/cache/dev/appDevDebugProjectContainer.php(16356): Doctrine\ORM\EntityManager-&gt;remove(Object(WellCommerce\Bundle\BannerBundle\Entity\Banner))
> 
> #13 /var/www/html/wellcommerce_git/src/WellCommerce/Bundle/CoreBundle/Manager/AbstractManager.php(89): DoctrineORMEntityManager_000000005b97372a00000000440374d7d2d48e650a3d652bfe99114b82822d15-&gt;remove(Object(WellCommerce\Bundle\BannerBundle\Entity\Banner))
> 
> #14 /var/www/html/wellcommerce_git/src/WellCommerce/Bundle/CoreBundle/Controller/Admin/AbstractAdminController.php(112): WellCommerce\Bundle\CoreBundle\Manager\AbstractManager-&gt;removeResource(Object(WellCommerce\Bundle\BannerBundle\Entity\Banner))
> 
> #15 [internal function]: WellCommerce\Bundle\CoreBundle\Controller\Admin\AbstractAdminController-&gt;deleteAction(1)
> 
> #16 /var/www/html/wellcommerce_git/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(153): call_user_func_array(Array, Array)
> 
> #17 /var/www/html/wellcommerce_git/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
> 
> #18 /var/www/html/wellcommerce_git/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(169): Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> 
> #19 /var/www/html/wellcommerce_git/web/app_dev.php(26): Symfony\Component\HttpKernel\Kernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request))
> 
> #20 {main}
> 


2.- I want to add a photo to banner form. I can add media widget with this code in Form/Admin/BannerFormBundle.php:
       

> $mediaData = $form->addChild($this->getElement('nested_fieldset', [
>             'name'  => 'media_data',
>             'label' => $this->trans('product.form.fieldset.photos')
>         ]));
>         
>         $mediaData->addChild($this->getElement('image', [
>             'name'         => 'foto',
>             'label'        => 'Foto',
>             'load_route'   => $this->getRouterHelper()->generateUrl('admin.media.grid'),
>             'upload_url'   => $this->getRouterHelper()->generateUrl('admin.media.add'),
>             'repeat_min'   => 0,
>             'repeat_max'   => 1,
>             'transformer'  => $this->getRepositoryTransformer('entity', $this->get('banner.repository')),
>             'session_id'   => $this->getRequestHelper()->getSessionId(),
>             'session_name' => $this->getRequestHelper()->getSessionName(),
>         ]));


But when I save the form, I get this error:

> The identifier id is missing for a query of WellCommerce\Bundle\BannerBundle\Entity\Banner 

Thsi is my Entity/Banner.php:

> 
> <?php
> /*
>  * WellCommerce Open-Source E-Commerce Platform
>  *
>  * This file is part of the WellCommerce package.
>  *
>  * (c) Adam Piotrowski <adam@wellcommerce.org>
>  *
>  * For the full copyright and license information,
>  * please view the LICENSE file that was distributed with this source code.
>  */
> 
> namespace WellCommerce\Bundle\BannerBundle\Entity;
> 
> use Doctrine\Common\Collections\Collection;
> use Knp\DoctrineBehaviors\Model\Blameable\Blameable;
> use Knp\DoctrineBehaviors\Model\Timestampable\Timestampable;
> use Knp\DoctrineBehaviors\Model\Translatable\Translatable;
> use WellCommerce\Bundle\CoreBundle\Entity\IdentifiableTrait;
> 
> /**
>  * Class Banner
>  *
>  * @author  Adam Piotrowski <adam@wellcommerce.org>
>  */
> class Banner implements BannerInterface
> {
>     use IdentifiableTrait;
>     use Translatable;
>     use Timestampable;
>     use Blameable;
>     
>     /**
>      * @var string
>      */
>     protected $foto;
>     
>     /**
>      * @var string
>      */
>     protected $texto;
>     
>     /**
>      * @var string
>      */
>     protected $link;
>     
>     /**
>      * @var int
>      */
>     protected $orden;
>     
>     /**
>      * @var bool
>      */
>     protected $intExt;
>     
> 
>     /**
>      * @return string
>      */
>     public function getFoto() : string
>     {
>         return $this->foto;
>     }
>     
>     /**
>      * @param string $foto
>      */
>     public function setFoto(string $foto)
>     {
>         $this->foto = $foto;
>     }
> 
>     /**
>      * @return string
>      */
>     public function getTexto() : string
>     {
>         return $this->texto;
>     }
>     
>     /**
>      * @param string $texto
>      */
>     public function setTexto(string $texto)
>     {
>         $this->texto = $texto;
>     }
> 
>     /**
>      * @return string
>      */
>     public function getLink() : string
>     {
>         return $this->link;
>     }
>     
>     /**
>      * @param string $link
>      */
>     public function setLink(string $link)
>     {
>         $this->link = $link;
>     }
> 
>     /**
>      * {@inheritdoc}
>      */
>     public function getOrden()
>     {
>         return $this->orden;
>     }
>     
>     /**
>      * {@inheritdoc}
>      */
>     public function setOrden($orden)
>     {
>         $this->orden = $orden;
>     }
> 
>      /**
>      * {@inheritdoc}
>      */
>     public function getIntExt() : bool
>     {
>         return $this->intExt;
>     }
>     
>     /**
>      * {@inheritdoc}
>      */
>     public function setIntExt(bool $intExt)
>     {
>         $this->intExt = $intExt;
>     }
> 
> }
> 


Can you help me please?
Thank you

**Comment by adampiotrowski** [comment]
Latest dev branch contains new WellCommerceBundleGenerator (wellcommerce:bundle:generate command) which creates a CRUD-like bundle.
