### ISSUE TITLE
Please   I can not install 

### ISSUE THREAD

**Issue by cookiesze** [WellCommerce/WellCommerce#109]
I do not understand 

Installation

As WellCommerce uses Composer to manage its dependencies, the recommended way to create a new project is to use it.

If you don't have Composer yet, download it following the instructions on http://getcomposer.org/ or just run the following command:

curl -s http://getcomposer.org/installer | php
Then, use the create-project command to generate a new WellCommerce application:

For developer/contributor edition use following command:

php composer.phar create-project wellcommerce/wellcommerce -s dev path/to/wellcommerce
Composer will install WellCommerce and all its dependencies under the path/to/wellcommerce directory. You will be asked to enter configuration parameters during the install process.

After the download is complete, run following command to create a database, install assets and import sample data:

cd path/to/wellcommerce
php app/console wellcommerce:install

Please Document the program

 .

**Comment by adampiotrowski** [comment]
@cookiesze What problems do you have? Don't know how to use Composer to install the app? Please explain better. It's a standard procedure for many PHP projects using Composer.

**Comment by cookiesze** [comment]
E:\xampp\htdocs\Myshop>composer install
> WellCommerce\Bundle\DistributionBundle\Composer\HerokuEnvironment::populateEnv
ironment
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.0 but your PHP version (5.6.11) does not sati
sfy that requirement.
  Problem 2
    - The requested PHP extension ext-intl * is missing from your system. Instal
l or enable PHP's intl extension.
  Problem 3
    - Installation request for ocramius/package-versions 1.0.4 -> satisfiable by
 ocramius/package-versions[1.0.4].
    - ocramius/package-versions 1.0.4 requires php ~7.0 -> your PHP version (5.6
.11) does not satisfy that requirement.
  Problem 4
    - Installation request for ocramius/proxy-manager 2.0.x-dev -> satisfiable b
y ocramius/proxy-manager[2.0.x-dev].
    - ocramius/proxy-manager 2.0.x-dev requires php ~7.0 -> your PHP version (5.
6.11) does not satisfy that requirement.
  Problem 5
    - ocramius/proxy-manager 2.0.x-dev requires php ~7.0 -> your PHP version (5.
6.11) does not satisfy that requirement.
    - doctrine/migrations dev-master requires ocramius/proxy-manager ^1.0|^2.0 -
> satisfiable by ocramius/proxy-manager[2.0.x-dev].
    - Installation request for doctrine/migrations dev-master -> satisfiable by
doctrine/migrations[dev-master].

**Comment by cookiesze** [comment]
I do not understand and I can not speak English
I try to install your code to learn.

**Comment by adampiotrowski** [comment]
@cookiesze You're using PHP 5.6.11 but WellCommerce requires 7.0. It's not possible to install it on older PHP versions, only 7.0 and 7.1 are supported.

**Comment by cookiesze** [comment]
I install xampp 7.0.9 / PHP 7.0.9

**Comment by cookiesze** [comment]
ok 
install 7.09 not support

**Comment by cookiesze** [comment]
Thk adampiotrowski 


I want to learn the web ^ ^

**Comment by cookiesze** [comment]
I have installed composer

**Comment by adampiotrowski** [comment]
@cookiesze It's not about installing the Composer. You have a lower PHP version when using CLI (Command Line Interface). It's a common problem if you have many installed PHP versions. 

You should search for instructions how to properly setup Xammp on Windows.

**Comment by cookiesze** [comment]
php composer.phar create-project wellcommerce/wellcommerce -s dev path/to/wellcommerce


E:\xampp2\htdocs>php composer.phar create-project wellcommerce/wellcommerce -s d
ev path/to/wellcommerce
Could not open input file: composer.phar

T T

**Comment by cookiesze** [comment]
I can not understand English, I 'mstupid

**Comment by cookiesze** [comment]
Thank you for your advice

**Comment by cookiesze** [comment]
Thank you and bye    ^ ^

**Comment by cookiesze** [comment]
Hello adampiotrowski  WellCommerce 
engine Symfony framework not laravel?       Yes or No ?

Thank you

**Comment by adampiotrowski** [comment]
We're using Symfony3.

**Comment by cookiesze** [comment]
c:\xampp\htdocs\WellCommerce>php app/console wellcommerce:install
PHP Warning:  require(C:\xampp\htdocs\WellCommerce\app/../vendor/autoload.php):
failed to open stream: No such file or directory in C:\xampp\htdocs\WellCommerce
\app\autoload.php on line 19

Warning: require(C:\xampp\htdocs\WellCommerce\app/../vendor/autoload.php): faile
d to open stream: No such file or directory in C:\xampp\htdocs\WellCommerce\app\
autoload.php on line 19
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\WellCommer
ce\app/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\ht
docs\WellCommerce\app\autoload.php on line 19

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\WellCommerce\ap
p/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\
WellCommerce\app\autoload.php on line 19
error 

Thank you for help

**Comment by cookiesze** [comment]
I give up 

Thank you for help
