### ISSUE TITLE
PHP conflcts with Symfony, resulting in 500 error

### ISSUE THREAD

**Issue by educate** [WellCommerce/WellCommerce#110]
Hi,
The first time I went to products list page after logging in, I found there was not **select box** in front of each product.
(Question updated) An internal server error occurs, what do I learn from the output and how to fix the problem? Thank you!

_[24-Sep-2016 02:31:04 UTC] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of WellCommerce\Bundle\ShopBundle\Repository\ShopRepository::resolve() must implement interface WellCommerce\Bundle\ShopBundle\Entity\ShopInterface, boolean returned in /var/lib/openshift/57d6a7567628e1fb73000233/app-root/runtime/repo/public/src/WellCommerce/Bundle/ShopBundle/Repository/ShopRepository.php:44
Stack trace:
#0 /var/lib/openshift/57d6a7567628e1fb73000233/app-root/runtime/repo/public/src/WellCommerce/Bundle/ShopBundle/EventListener/ShopSubscriber.php(50): WellCommerce\Bundle\ShopBundle\Repository\ShopRepository->resolve(0, 'www.mydiscovery...')
#1 [internal function]: WellCommerce\Bundle\ShopBundle\EventListener\ShopSubscriber->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#2 /var/lib/openshift/57d6a7567628e1fb73000233/app-root/runtime/repo/public/app/cache/prod/classes.php(2172): call_user in /var/lib/openshift/57d6a7567628e1fb73000233/app-root/runtime/repo/public/src/WellCommerce/Bundle/ShopBundle/Repository/ShopRepository.php on line 44_

**Comment by adampiotrowski** [comment]
@educate Change doctrine.server_version to 5.5 in your app/config/parameters.yml file. If it won't help, please update MySQL to 5.6. MySQL 5.7 isn't supported yet.

**Comment by educate** [comment]
that's no good, mysql v5.7 is not officially supported yet, did somebody report to you it was not compatible in use?

**Comment by educate** [comment]
This is no longer a problem, the system has the amazing capacity to self heal, now works regularly. Select box in the front of each product is missing, may be due to wrong configuration between nginx and apache.
