### ISSUE TITLE
Issue Creating User (500 Internal Server Error - ClassNotFoundException)

### ISSUE THREAD

**Issue by anjo-swe** [WellCommerce/WellCommerce#112]
Ran the following commands to install latest version

```
php composer.phar create-project wellcommerce/wellcommerce path/to/wellcommerce dev-development
php app/console wellcommerce:install
```

When i then tried to create a user (used app_dev.php) i got this error:

```
Attempted to load class "UniqueUsernameValidator" from namespace "WellCommerce\Bundle\ClientBundle\Validator\Constraints".
Did you forget a "use" statement for "WellCommerce\Bundle\ClientBundle\Validator\UniqueUsernameValidator"?
500 Internal Server Error - ClassNotFoundException
```

Trace:

```
     */
    protected function getClient_Validator_UniqueUsernameService()
    {
        return $this->services['client.validator.unique_username'] = new \WellCommerce\Bundle\ClientBundle\Validator\Constraints\UniqueUsernameValidator($this->get('client.repository'), $this->get('router.helper'));
    }
    /**
```

**Comment by adampiotrowski** [comment]
@anjo-swe It looks like we've broken this in latest update. I'll fix it tomorrow morning. 

BTW. At this moment it's better to use Git version instead of composer. It'll be far easier to update to newest version.

**Comment by anjo-swe** [comment]
Ok, i actually started with that just a few min ago :)

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package twig/extensions 1.3.x-dev exists as twig/extensions[dev-master, 1.4.x-dev, dev-twig20-compat, v1.0.0, v1.0.0-alpha, v1.0.1, v1.1.0, v1.2.0, v1.3.0, v1.4.0] but these are rejected by your constraint.
```

Got this issue so just changed to `1.4.x-dev` in my local version but maybe something you want to fix at the same time

**Comment by adampiotrowski** [comment]
Yup, this deprecation was introduced by Twig few days ago. It'll be also fixed tomorrow. There aren't aby BC breaks, mostly fixes.

**Comment by anjo-swe** [comment]
Any update?

**Comment by adampiotrowski** [comment]
@anjo-swe I pushed recently to our repository. Check please if it works now.

**Comment by adampiotrowski** [comment]
@anjo-swe I see in our sentry something like this

Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to WellCommerce\Bundle\ReviewBundle\Twig\Extension\ReviewExtension::__construct() must be an instance of WellCommerce\Bundle\ReviewBundle\Repository\ReviewRecommendationRepositoryInterface, none given, called in /Applications/MAMP/htdocs/wellcommerce1/app/cache/prod/appProdProjectContainer.php on line 13142
  File "/Applications/MAMP/htdocs/wellcommerce1/src/WellCommerce/Bundle/ReviewBundle/Twig/Extension/ReviewExtension.php", line 35, in __construct
    public function __construct(ReviewRecommendationRepositoryInterface $repository)
  File "/Applications/MAMP/htdocs/wellcommerce1/app/cache/prod/appProdProjectContainer.php", line 13142, in getTwig_Extension_ReviewService
    return $this->services['twig.extension.review'] = new \WellCommerce\Bundle\ReviewBundle\Twig\Extension\ReviewExtension();
  File "/Applications/MAMP/htdocs/wellcommerce1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php", line 275, in get
    $service = $this->$method();
  File "/Applications/MAMP/htdocs/wellcommerce1/app/cache/prod/appProdProjectContainer.php", line 12862, in getTwigService
    $instance->addExtension($this->get('twig.extension.review'));
  File "/Applications/MAMP/htdocs/wellcommerce1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php", line 275, in get
    $service = $this->$method();
...
(12 additional frame(s) were not displayed)

Is it you? What have you done :D

**Comment by adampiotrowski** [comment]
It looks like you didn't cleared the cache after updating the application. Repository service is missing but it's registered during boot process. Many services are auto-registered through compiler passes.

**Comment by anjo-swe** [comment]
Yes, that was me :)

I tried using app_dev.php and it worked.

How do i clear the cache after getting new code?

/A

**Comment by adampiotrowski** [comment]
In two ways:

- manually remove app/cache/dev and app/cache/prod directories

or

- run cache:clear command from console ie. app/console cache:clear

I prefer first method, it's faster.

**Comment by anjo-swe** [comment]
Looks good!
