### ISSUE TITLE
Fail to add product to cart

### ISSUE THREAD

**Issue by anjo-swe** [WellCommerce/WellCommerce#113]
```[2016-09-29 22:25:39] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.weight AS weight_2, t0.symbol AS symbol_3, t0.stock AS stock_4, t0.modifier_type AS modifier_type_5, t0.modifier_value AS modifier_value_6, t0.hierarchy AS hierarchy_7, t0.enabled AS enabled_8, t0.sell_price_net_amount AS sell_price_net_amount_9, t0.sell_price_gross_amount AS sell_price_gross_amount_10, t0.sell_price_tax_amount AS sell_price_tax_amount_11, t0.sell_price_tax_rate AS sell_price_tax_rate_12, t0.sell_price_currency AS sell_price_currency_13, t0.sell_price_discounted_net_amount AS sell_price_discounted_net_amount_14, t0.sell_price_discounted_gross_amount AS sell_price_discounted_gross_amount_15, t0.sell_price_discounted_tax_amount AS sell_price_discounted_tax_amount_16, t0.sell_price_valid_from AS sell_price_valid_from_17, t0.sell_price_valid_to AS sell_price_valid_to_18, t0.createdAt AS createdAt_19, t0.updatedAt AS updatedAt_20, t0.product_id AS product_id_21, t0.availability_id AS availability_id_22, t0.photo_id AS photo_id_23 FROM variant t0 WHERE t0.id = ?' with params [0]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.enabled' in 'field list'" at /Applications/MAMP/htdocs/wellcommerce1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.weight AS weight_2, t0.symbol AS symbol_3, t0.stock AS stock_4, t0.modifier_type AS modifier_type_5, t0.modifier_value AS modifier_value_6, t0.hierarchy AS hierarchy_7, t0.enabled AS enabled_8, t0.sell_price_net_amount AS sell_price_net_amount_9, t0.sell_price_gross_amount AS sell_price_gross_amount_10, t0.sell_price_tax_amount AS sell_price_tax_amount_11, t0.sell_price_tax_rate AS sell_price_tax_rate_12, t0.sell_price_currency AS sell_price_currency_13, t0.sell_price_discounted_net_amount AS sell_price_discounted_net_amount_14, t0.sell_price_discounted_gross_amount AS sell_price_discounted_gross_amount_15, t0.sell_price_discounted_tax_amount AS sell_price_discounted_tax_amount_16, t0.sell_price_valid_from AS sell_price_valid_from_17, t0.sell_price_valid_to AS sell_price_valid_to_18, t0.createdAt AS createdAt_19, t0.updatedAt AS updatedAt_20, t0.product_id AS product_id_21, t0.availability_id AS availability_id_22, t0.photo_id AS photo_id_23 FROM variant t0 WHERE t0.id = ?' with params [0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.enabled' in 'field list' at /Applications/MAMP/htdocs/wellcommerce1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.enabled' in 'field list' at /Applications/MAMP/htdocs/wellcommerce1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.enabled' in 'field list' at /Applications/MAMP/htdocs/wellcommerce1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []```

**Comment by adampiotrowski** [comment]
After clearing the cache you should also run Doctrine migrations

app/console doctrine:migrations:diff

and then

app/console doctrine:migrations:migrate

PS. RC & stable versions will be auto-updated after new release is downloaded & installed ;).

**Comment by anjo-swe** [comment]
Thanks
