### ISSUE TITLE
What's the recommend approach to add a TMS to the Demo site?

### ISSUE THREAD

**Issue by anjo-swe** [WellCommerce/WellCommerce#114]
Example: I want to add Google Tag Manager

Then their installation guide mentions 2 pieces:

1) Paste this code as high in the `<head>` of the page as possible

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-xxx');</script>
<!-- End Google Tag Manager -->
```

2) Additionally, paste this code immediately after the opening `<body> `tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-xxx"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by adampiotrowski** [comment]
Ping @adrianpotepa @rmartonik

**Comment by anjo-swe** [comment]
Any ideas on how to solve it today would be great, trying to setup a demo for early next week

**Comment by adrianpotepa** [comment]
Hello Andreas!

You have to place #2 code after <body> tag, #1 script has to be placed after #2.

Example:

<body>
	


In demo template, you have to place it in layout.html.twig (https://github.com/WellCommerce/WellCommerce/blob/development/web/themes/wellcommerce-default-theme/templates/WellCommerceAppBundle/Front/layout.html.twig <https://github.com/WellCommerce/WellCommerce/blob/development/web/themes/wellcommerce-default-theme/templates/WellCommerceAppBundle/Front/layout.html.twig>).


		
ADRIAN POTĘPA
Lead Front-end Developer

adrian@wellcommerce.org <mailto:adrian@wellcommerce.org>
www.wellcommerce.org <http://wellcommerce.org/>
www.wellcommerce.org/pro <http://wellcommerce.org/pro>

**Comment by anjo-swe** [comment]
Thanks for your answer @adrianpotepa 

Will try it out during the weekend and let you know how it goes

**Comment by anjo-swe** [comment]
Works well, thanks
