### ISSUE TITLE
Exposing more information about logged in users inside cookies

### ISSUE THREAD

**Issue by anjo-swe** [WellCommerce/WellCommerce#116]
Currently there's a cookie named `WELLSESSID` but i would like to expose more information (e.g. client id, email used during login etc.)

Goal:
* When the user successfully logs in, then these cookies should be set

Any ideas on how to best solve this? I looked at using http://api.symfony.com/2.8/Symfony/Component/Security/Http/Authentication/AuthenticationSuccessHandlerInterface.html but not sure what next steps would be.

Side note, tried to inject a Logger into LoginFailureHandler as an initial test but didn't really get there.

services.yml
```
    client.failure.handler:
        class: WellCommerce\Bundle\ClientBundle\Handler\LoginFailureHandler
        arguments: ['@router', front.client.login, '@logger']
```

LoginFailureHandler.php
```
    public function __construct(RouterInterface $router, $loginRoute, LoggerInterface $logger)
    {
        $this->router     = $router;
        $this->loginRoute = $loginRoute;
        $this->logger     = $logger;
    }
```

But it's always null when i want to use it, any clue about that one?

**Comment by adampiotrowski** [comment]
I assume you want to show properties of the Client object in your templates. Simply use 

`{% if app.user and is_granted('ROLE_CLIENT') %}`

to check if the client is logged in and then ie.

{{ app.user.clientDetails.username }} to show the login 
{{ app.user.client.id }} to show the ID

You can simply check which properties are accessible in Client entity and embeddables inside it (clientDetails, clientContactDetails, billingAddress, shippingAddress).

There's no need to use getters, Twig will auto-magically resolve the methods 

{{ app.user.clientDetails.username }} equals to {{ app.user.getClientDetails().getUsername() }}

**Comment by anjo-swe** [comment]
Awesome
