### ISSUE TITLE
Unable to create the cache directory

### ISSUE THREAD

**Issue by educate** [WellCommerce/WellCommerce#117]
Hi,
I tried to install wellcommerce with apache, /home/apache/htdocs is my project directory, unfortunately, got an internal server error, the detail is as below for your reference, the project directory permission was set to be 755.

[Thu Oct 06 11:05:54.819740 2016] [:error] [pid 16741] [client 108.162.215.193:3
0035] PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache di
rectory (/home/apache/htdocs/app/cache/prod)\n in /home/apache/htdocs/vendor/sym
fony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:552\nStack trace:\n#0 /
home/apache/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kerne
l.php(476): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /home/a
pache/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(
117): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /home/ap
ache/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(1
66): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /home/apache/htdocs/web/
app.php(16): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Comp
onent\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /home/apache/htdocs/ven
dor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 552

I have another question, should I change directoryindex to app.php in httpd.conf?
```
<IfModule dir_module>
    DirectoryIndex index.php index.html
</IfModule>
```

Thank you!

**Comment by adampiotrowski** [comment]
@educate Please use development environment i.e. www.mydomain.com/**app_dev.php/**admin/dashboard/index so you can see the errors. 

Which version/tag/branch are you using?

**Comment by educate** [comment]
Thanks for your quick reply!
master, the stable version, I think.  I follow your instruction to install.
when I configure nginx to ge wellcommerce running under Nginx, I used
# PROD
    location ~ ^/app\.php(/|$) {
...

Should I use # DEV instead?

**Comment by adampiotrowski** [comment]
@educate You should change the folder permissions but also the owner. By default it'll be www-data (you must check in httpd.conf). Then run following commands in your project's root directory

> chmod -R 755 app/cache/*
> chmod -R 755 app/logs/*
> chmod -R 755 web/media/*
> chown -R www-data:www-data app/cache/*
> chown -R www-data:www-data app/logs/*
> chown -R www-data:www-data web/media/*

**Comment by educate** [comment]
it works now, I just make apache user owns project directory and web directory and change those directories' permission as well, Thank you for your advice!
