### ISSUE TITLE
Plz Help me

### ISSUE THREAD

**Issue by cookiesze** [WellCommerce/WellCommerce#120]
Plz 
Create sample prarmeters 

Thk

parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: well
    database_user: root
    database_password: null
    mailer_host: 127.0.0.1
    mailer_from: smtp
    mailer_port: 25
    mailer_user: cookiesz.blurz@gmail.com
    mailer_password: 
    prod_log_path: 
    locale: 
    secret: 
    debug_toolbar: true
    debug_redirects: false
    doctrine.server_version: 5.6
    fallback_theme: wellcommerce-default-theme
    fallback_hostname: localhost
    developer_mode.ip: 127.0.0.1
    search_engine: google
    php_binary_path: null
    facebook_app_id: null
    facebook_app_secret: null
    pdo.db_options:
        db_table: session
        db_id_col: session_id
        db_data_col: session_value
        db_time_col: session_time

**Comment by adampiotrowski** [comment]
I don't understand what is the problem. Please be more specific.

**Comment by cookiesze** [comment]
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "kernel.logs dir" must be defined. in E:\xampp\htdocs\well\app\cache\prod\appProdProjectContainer.php:14546 Stack trace: #0 E:\xampp\htdocs\well\app\cache\prod\appProdProjectContainer.php(7612): appProdProjectContainer->getParameter('kernel.logs dir') #1 E:\xampp\htdocs\well\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php(275): appProdProjectContainer->getMonolog_Handler_NestedService() #2 E:\xampp\htdocs\well\app\cache\prod\appProdProjectContainer.php(7599): Symfony\Component\DependencyInjection\Container->get('monolog.handler...') #3 E:\xampp\htdocs\well\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php(275): appProdProjectContainer->getMonolog_Handler_MainService() #4 E:\xampp\htdocs\well\app\cache\prod\appProdProjectContainer.php(7421): Symfony\Component\DependencyInjection\Container->get('monolog.handler...') #5 E:\xampp\htdocs\well\vendor\symfony\sy in E:\xampp\htdocs\well\app\cache\prod\appProdProjectContainer.php on line 14546
