### ISSUE TITLE
Can not add image to Media library

### ISSUE THREAD

**Issue by educate** [WellCommerce/WellCommerce#121]
Hi,
Log in to your demo site, go to CMS -> Media management, click Add button, then get the dreaded 500 Internal Server Error
I thought this only happened in my site, please fix it.

**Comment by argoitz** [comment]
Hi,
i think this issue is not fixed yet because I'm triing to see it in http://demo.wellcommerce.org/admin/cms/media/add and I get a 500 internal server error.

Can you fix it or say how to solve this issue?
Thank you.
