### ISSUE TITLE
500 error on http://demo.wellcommerce.org/client/address/index

### ISSUE THREAD

**Issue by argoitz** [WellCommerce/WellCommerce#127]
Hi there,
when you save changes the page shows an "500 Internal Server Error". I try to save changes in my machine and i get this error: 

> An exception has been thrown during the rendering of a template ("Expected argument of type "string", "NULL" given") in WellCommerceClientBundle:Front\ClientAddressBook:index.html.twig at line 10.

Can you fix it, or say how can i fix it?
Thank you.

**Comment by rafalrudnicki** [comment]
Hi,
I think there is a problem with the validation form, some fields are missing in form (companyName,vatId,state)

**Comment by argoitz** [comment]
Thank you very much.
Issue fixed.
