### ISSUE TITLE
Problem with confirm order

### ISSUE THREAD

**Issue by rafalrudnicki** [WellCommerce/WellCommerce#128]
I have problem wit confirm order (route name front.order_confirm.index). I have error

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INT)) AS last_order FROM orders WHERE confirmed = 1' at line 1

I modify method generateOrderNumber() in class  WellCommerce\Bundle\OrderBundle\Generator\OrderNumberGenerator

old line
$sql  = "SELECT MAX(CAST(orders.number AS **INT**)) AS last_order FROM orders WHERE confirmed = 1";

ne wline
$sql  = "SELECT MAX(CAST(orders.number AS **UNSIGNED**)) AS last_order FROM orders WHERE confirmed = 1";

see
http://dev.mysql.com/doc/refman/5.6/en/cast-functions.html

Now work great

**Comment by adampiotrowski** [comment]
@rafalrudnicki Could you please submit a PR with this fix?
