### ISSUE TITLE
suhosin.executor.include.whitelist setting is incorrect

### ISSUE THREAD

**Issue by chef09** [WellCommerce/WellCommerce#134]
curl -s http://getcomposer.org/installer | php

suhosin.executor.include.whitelist = phar

**Comment by chef09** [comment]
hehe solved:
add suhosin.executor.include.whitelist = phar in /php.ini or php -d = value {make a value on fly}

**Comment by adampiotrowski** [comment]
Problem is not related to WellCommerce.
