### ISSUE TITLE
Install on Vagrant

### ISSUE THREAD

**Issue by rafaelcavalcanti** [WellCommerce/WellCommerce#137]
I've trying to install a lot of times, but every attempt i give a error. The list:

1. - I change the vendor folder (composer.json: vendor-dir and cache-dir) to another path for give best performance with Vagrant (bento/centos-7.2) and Windows.
2. - Change de app/autoload.php to catch the new vendor path.
3. - **php app/console wellcommerce:app:install** and them error to remover cache folder, even when i set 777.
4. Front-end runs ok, but the Admin.... give me the login form, but i can't access (u: admin / p: admin). 

Another attempt:
1. **git clone https://github.com/WellCommerce/WellCommerce** outside of **config.vm.synced_folder** 
2. **composer install & php app/console wellcommerce:app:install** 
3. Disable protection of REMOTE_ADDR... from app_dev.php, set umask(0000), set chmod 777 app(cache/logs/sessions), tail -f app/logs/dev.log and everything runs fine.... until i try to access admin http://shop/app_dev.php/admin give me a blank page and no message in the log to guide me. Just a deprecated alerts:
- php.INFO: User Deprecated: The Symfony\Bridge\Monolog\Handler\DebugHandler class is deprecated since version 3.2 ...
-  php.INFO: User Deprecated: Defining the initRuntime() method in the "report" extension is deprecated since version 1.23...

What i forgot?
Best regards.
Rafael

**Comment by adampiotrowski** [comment]
@rafaelcavalcanti Hi Rafael! Do you see a totally blank page or only a header with grey background after accessing /admin? 

As non-logged administrator you should be redirected from /admin to /admin/user/login. Try to access http://shop/app_dev.php/admin/user/login manually. It could be something related to firewall and redirection in our routing.

Btw. are you're using our development or master branch?

**Comment by rafaelcavalcanti** [comment]
@adampiotrowski Hi Adam, I see just a header (See image). And when i access [](http://shop/app_dev.php/admin) there are a automatic redirect to [](http://shop/app_dev.php/admin/user/login) . Even when a i tried manually  there are the same issue. I will try on a cloud (CentOS 7) either to be sure. 

I'm using a master branch.  

![wellcommerce](https://cloud.githubusercontent.com/assets/12388/22828132/69ed851c-ef7a-11e6-8422-7b9ca48da4cd.jpg)

Thanks.

**Comment by adampiotrowski** [comment]
@rafaelcavalcanti Please switch to **development** branch. Master wasn't updated since few months.  

After switching run wellcommerce:app:install again.

**Comment by rafaelcavalcanti** [comment]
@adampiotrowski  Hi, Humm ok Adam, i will try. I give you a feedback. 

Thanks.

**Comment by rafaelcavalcanti** [comment]
@adampiotrowski unfortunately there is no successful and i definitely don't know what to do. I've already tried:
- Windows 7 64bit + Xamp (php 7.1.1 + Apache 2.4.25 + MariaDB 10.1.21)
- Vagrant (Windows) with: box bento/centos-7.2, php 7.0.15 + Apache 2.4.6 + MariaDb 10.1.21
- Cloud (Digital Ocean) with: CentOS 7 + php 7.1.1 + Apache 2.2.15 + Mysql 5.5.54

Thanks for the help.
Best regards.

**Comment by adampiotrowski** [comment]
@rafaelcavalcanti The same error as previously, only header on the login screen? 

I think it could be something related to symlinks used in assets:install command. Could you please try again but instead of using wellcommerce:app:install, run following commands manually

```
php app/console doctrine:schema:create
php app/console doctrine:fixtures:load -n
php app/console assets:install
php app/console bazinga:js-translation:dump
php app/console fos:js-routing:dump
php app/console cache:warmup
```

Or only those to regenerate the assets

```
php app/console assets:install
php app/console bazinga:js-translation:dump
php app/console fos:js-routing:dump
```

**Comment by adampiotrowski** [comment]
@rafaelcavalcanti After long investigation ;) I found the issue. It was related to the latest willdurand/js-translation-bundle update. I downgraded its version in our dev branch, now it works fine.

**Comment by rafaelcavalcanti** [comment]
@adampiotrowski, Hi Adam. I found the problem!

Was missed a "**;**" on the end of the file **web/bundles/bazingajstranslation/js/translator.min.js** and when it is uglify in **libs.js** we getting a error from code bellow.

Thanks.

**Comment by adampiotrowski** [comment]
@rafaelcavalcanti https://www.youtube.com/watch?v=S9RVS8cjNN0 ! :)

**Comment by rafaelcavalcanti** [comment]
@adampiotrowski  kkk Thanks a lot! ;) Best regards!

**Comment by rafaelcavalcanti** [comment]
@adampiotrowski, Hi Adam. Today when I decided to debug the code i found the problem!

Was missed a "**;**" on the end of the file **web/bundles/bazingajstranslation/js/translator.min.js** and when it is uglify in **libs.js** we getting a error from code bellow.

Thanks.
