### ISSUE TITLE
Slug Generator error

### ISSUE THREAD

**Issue by rafaelcavalcanti** [WellCommerce/WellCommerce#138]
Hi, there is a issue on Slug Generator. I found the soluction on **src/WellCommerce/Bundle/RoutingBundle/Resources/config/services.yml**

The service is typing with '**admin**' folder that not exists, causing exception: 

Attempted to load class "RouteController" from namespace  "WellCommerce\Bundle\RoutingBundle\Controller\Admin". Did you forget a "use" statement for another namespace?

I remove the word admin from the namespace of the controller (**src/WellCommerce/Bundle/RoutingBundle/Controller/RouteController.php**) 
and the service (**route.controller**) and works perfectly. 

I don't know if that was predicted by the future updates, but for now works for me. 
Thanks.

**Comment by adampiotrowski** [comment]
@rafaelcavalcanti As you see there're many changes lately, mostly with separating core bundles ;). I fixed this already but didn't have enough time to merge the fixes. Your workaround is enough.
