### ISSUE TITLE
Debug toolbar not found

### ISSUE THREAD

**Issue by AlexBDev** [WellCommerce/WellCommerce#142]
Hi,
I've recently installed your project, the install has been done well but the debug toolbar are missing.
A message in popup say "Error debug toolbar not found 404". All others ressources load perfectly.
I work under docker, i can provide more informations if needed. 

Do you have any idea ? 

PS : Great job :)

**Comment by adampiotrowski** [comment]
Hi @AlexBDev 

IIRC it can be related to long running processes or timeouts during the "kernel.terminate event". We have only two standard Symfony listeners so i think it's something in ProfilerListener::onKernelTerminate method which fetches the data from all registered collectors.

 ------- ----------------------------------------------------------------------------------- ----------
  Order   Callable                                                                            Priority
 ------- ----------------------------------------------------------------------------------- ----------
  #1      Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate()   0
  #2      Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelTerminate()    -1024
 ------- ----------------------------------------------------------------------------------- ----------

Are you using dev environment? Pls give me more information about the configuration of Docker environment.

**Comment by adampiotrowski** [comment]
@AlexBDev I received a stack trace from our Sentry. Is it yours?

Exception

Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Symfony\Component\HttpKernel\EventListener\dump()
  File "/usr/share/nginx/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php", line 108, in onKernelTerminate
    dump($event);
  File "/usr/share/nginx/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php", line 106, in __invoke
    call_user_func($this->listener, $event, $eventName, $this->dispatcher ?: $dispatcher);
  File "/usr/share/nginx/html/app/cache/dev/classes.php", line 3301, in doDispatch
    call_user_func($listener, $event, $eventName, $this);
  File "/usr/share/nginx/html/app/cache/dev/classes.php", line 3216, in dispatch
    $this->doDispatch($listeners, $eventName, $event);
  File "/usr/share/nginx/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php", line 136, in dispatch
    $this->dispatcher->dispatch($eventName, $event);
...
(3 additional frame(s) were not displayed)
Request

URL	http://localhost:8080/app_dev.php/js/routing
Method	GET
Query	callback=fos.Router.setData
User

ID:	3c437574a603343b2776182292d83741
IP Address:	172.18.0.1
Sf2 Attributes	{'_locale': 'en', '_security_admin': '[Filtered]'}
Sf2 Flashes	[]
Sf2 Meta	{'c': 1490948450, 'u': 1490962348, 'l': '0'}
Message

Call to undefined function Symfony\Component\HttpKernel\EventListener\dump()
Tags

browser = Chrome 53.0  device = Other  level = fatal  logger = php os = Linux  sentry:user = id:3c437574a603343b2776182292d83741 server_name = dde25d41a8ae  site = localhost url = http://localhost:8080/app_dev.php/js/routing

**Comment by AlexBDev** [comment]
Thank for your reply.
Yes, it's my log, but i was investigating on the problem the dump is a mistake and not related to the problem.

Here my dockerfiles
[docker.zip](https://github.com/WellCommerce/WellCommerce/files/885578/docker.zip)

**Comment by AlexBDev** [comment]
Ok this [commit](https://github.com/WellCommerce/OrderBundle/commit/dd8621a92a74a29e10cbad3f69500dc641ea013a) fix this issue ! There's no more problems.

**Comment by adampiotrowski** [comment]
@AlexBDev I pushed this fix yesterday :). Pls run composer update to get all fixes.
