### ISSUE TITLE
Cant add locale 

### ISSUE THREAD

**Issue by argoitz** [WellCommerce/WellCommerce#153]
Hi there, 
I want to add a new locale to the shop, and I'm trying with this command:
`php app/console wellcommerce:locale:add`

When i execute it, I get this error:

> [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "wellcommerce:locale" namespace.
  Did you mean one of these?
      wellcommerce:admin
      wellcommerce:system
      wellcommerce:search
      wellcommerce:order
      wellcommerce:doctrine
      wellcommerce:package
      wellcommerce:bundle
      wellcommerce

How can I add a new locale?
Thank you.

**Comment by diversantvlz** [comment]
in admin panel /admin/configuration/locale/index

**Comment by argoitz** [comment]
in admin panel when i go to add locale "/admin/configuration/locale/add" I get this message:

> Add a locale
Adding a new locale requires that all translatable records will be copied to ensure database consistency. Please use following console command:

> php app/console wellcommerce:locale:add
> 
> You will be asked to choose source and target locale. Soon after the new locale is created, all related records will be copied automatically.

**Comment by adampiotrowski** [comment]
@argoitz Ah, we changed the command namespace. Thanks for reporting this. 

**Use app/console locale:add**

You can always use app/console to display all available command. In locale namespace there're only two.

locale
  locale:add                              Adds a new locale and copies translatable entities
  locale:delete                           Deletes a locale and related translatable entities

**Comment by argoitz** [comment]
Thank you @adampiotrowski. 
Thi works perfect.
