### ISSUE TITLE
Duplicating SimilarProductBundle get ClassNotFoundException

### ISSUE THREAD

**Issue by argoitz** [WellCommerce/WellCommerce#156]
Hi @adampiotrowski or Anyone that can help me.
I'm duplicating SimilarProductBundle and renaming to create a packProductBundle to assign a group of product to one product and create a pack.
I duplicate SimilarProductBundle but now I'm getting this error:

> Attempted to load class "WellCommercePackProductBundle" from namespace "WellCommerce\Bundle\PackProductBundle".
Did you forget a "use" statement for "WellCommerce\Bundle\PackProductBundle\WellCommercePackProductBundle"?

This is the file list that I copy or edit to insert this PackProductBundle reference:

> /vendor/composer/autoload_psr4.php:31:
/vendor/composer/autoload_static.php:62:
/vendor/composer/autoload_static.php:281:
/vendor/wellcommerce/pack-product-bundle/Enhancer/ProductMappingEnhancer.php:13:
/vendor/wellcommerce/pack-product-bundle/README.md:1:
/vendor/wellcommerce/pack-product-bundle/Service/Layout/Configurator/PackProductBoxConfigurator.php:13:
/vendor/wellcommerce/pack-product-bundle/Service/Layout/Configurator/PackProductBoxConfigurator.php:16:
/vendor/wellcommerce/pack-product-bundle/Service/Layout/Configurator/PackProductBoxConfigurator.php:21:
/vendor/wellcommerce/pack-product-bundle/Service/Layout/Configurator/PackProductBoxConfigurator.php:25:
/vendor/wellcommerce/pack-product-bundle/Service/Layout/Configurator/PackProductBoxConfigurator.php:27:
/vendor/wellcommerce/pack-product-bundle/Service/Layout/Configurator/PackProductBoxConfigurator.php:34:
/vendor/wellcommerce/pack-product-bundle/WellCommercePackProductBundle.php:13:
/vendor/wellcommerce/pack-product-bundle/WellCommercePackProductBundle.php:19:
/vendor/wellcommerce/pack-product-bundle/WellCommercePackProductBundle.php:23:
/vendor/wellcommerce/pack-product-bundle/Resources/config/services.yml:11: 
/vendor/wellcommerce/pack-product-bundle/Resources/config/services.yml:17:
/vendor/wellcommerce/pack-product-bundle/Resources/config/services.yml:22:
/vendor/wellcommerce/pack-product-bundle/Resources/config/services.yml:29:
/vendor/wellcommerce/pack-product-bundle/Resources/config/services.yml:34:
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductDoctrineSubscriber.php:13:
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductDoctrineSubscriber.php:21:
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductDoctrineSubscriber.php:25:
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductDoctrineSubscriber.php:49:
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductDoctrineSubscriber.php:50:
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductSubscriber.php:13:
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductSubscriber.php:22: 
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductSubscriber.php:26:
/vendor/wellcommerce/pack-product-bundle/EventListener/PackProductSubscriber.php:40: 
/vendor/wellcommerce/pack-product-bundle/composer.json:6: 
/vendor/wellcommerce/pack-product-bundle/composer.json:24:
/vendor/wellcommerce/pack-product-bundle/composer.json:25:
/vendor/wellcommerce/pack-product-bundle/composer.json:29:
/vendor/wellcommerce/pack-product-bundle/Controller/Box/PackProductBoxController.php:13:
/vendor/wellcommerce/pack-product-bundle/Controller/Box/PackProductBoxController.php:24:
/vendor/wellcommerce/pack-product-bundle/Controller/Box/PackProductBoxController.php:28:
/vendor/wellcommerce/pack-product-bundle/Controller/Box/PackProductBoxController.php:54:
/vendor/wellcommerce/pack-product-bundle/DependencyInjection/Configuration.php:12:
/vendor/wellcommerce/pack-product-bundle/DependencyInjection/WellCommercePackProductExtension.php:13:
/vendor/wellcommerce/pack-product-bundle/DependencyInjection/WellCommercePackProductExtension.php:18:
/vendor/wellcommerce/pack-product-bundle/DependencyInjection/WellCommercePackProductExtension.php:22:
/vendor/wellcommerce/standard-edition-bundle/WellCommerceStandardEditionBundle.php:42: 
/vendor/wellcommerce/standard-edition-bundle/Resources/config/config.yml:24: 
/vendor/wellcommerce/standard-edition-bundle/Resources/config/config.yml:67:  
/vendor/wellcommerce/standard-edition-bundle/Resources/config/config.yml:105:  
/vendor/wellcommerce/standard-edition-bundle/DataFixtures/ORM/LoadPackProductData.php:19: 
/vendor/wellcommerce/standard-edition-bundle/DataFixtures/ORM/LoadPackProductData.php:23:
/vendor/wellcommerce/standard-edition-bundle/DataFixtures/ORM/LoadPackProductData.php:36: 

I dont know where can i find the error and how to fix it. 
Please help.

Thank you

**Comment by adampiotrowski** [comment]
@argoitz As i see you copied all files directly in vendor directory so it won't work. You should copy all files from source directory (vendor/wellcommerce/similar-product-bundle) to src/WellCommerce/PackProductBundle and then replace the namespaces and file names. You can also use own namespace and folder ie. src/Argoitz/ProductPackBundle 

When using standard-edition all core bundles are installed into vendor directory. Look at the main WellCommerce/WellCommerce to see how the base structure looks like.

**Comment by argoitz** [comment]
Thank you @adampiotrowski, I insert PackProductBundle into src/Argoitz/Bundle and change the namespaces in this folder and the reference in vendor/wellcommerce/standard-edition-bundle/WellCommerceStandardEditionBundle.php and the error is fixed.
I'm learning a lot of symfony with wellcommerce project.
Thank you.
