### ISSUE TITLE
Change algolia account

### ISSUE THREAD

**Issue by argoitz** [WellCommerce/WellCommerce#158]
Hi @adampiotrowski, I'm getting this error when i search anything:

> Operations quota exceeded, change plans to get more Operations.

I create a new account in algolia and I set the credentials into "admin->Configuration->System configuration->Algolia setting", but now I'm getting another error because I don't know what to set into Parameters->search_index_prefix.
This is the error:

> Index wellcommerce_f349d6cd64c1f07a6ef6dab6aa228ef418ddcdd0_en_product does not exist

What do I have to put in this (Parameters->search_index_prefix.) field?

Thank you

**Comment by argoitz** [comment]
Hi, I fix it creating a index in algolia with "videosecurity_en_product" name, but now i cant execute app/console wellcommerce:search:reindex command. I get this error:
```
 [AlgoliaSearch\AlgoliaException]
  Method not allowed with this API key

```

Help please.
Thank you

**Comment by adampiotrowski** [comment]
@argoitz Please create your own Algolia account (https://www.algolia.com). They offer a free plan (up to 10k records). Then go to the Global configuration in the administration area and set new credentials 
http://awesomescreenshot.com/01a6bhgj94

**Comment by argoitz** [comment]
Hi @adampiotrowski, I create a new account in algolia and I set "Appication ID" and "Search-Only API Key" y Global configuration area.
Now when i try to execute "app/console wellcommerce:search:reindex" I'm getting this error:

> [AlgoliaSearch\AlgoliaException]
  Method not allowed with this API key

How can I execute reindex to index my products?
Thank you

**Comment by argoitz** [comment]
Hi @adampiotrowski , I set Global configuration credentials with "Application ID" and "Admin API Key" values. 
I have this index:
![image](https://cloud.githubusercontent.com/assets/19209969/26716904/9f1c73f2-477b-11e7-924c-da26767b9d0b.png)

Now, when I try to reindex, I get this error:

> [RuntimeException]
  Unable to get a property on a non-object.

and this action, removes me the "_en" index: 
![image](https://cloud.githubusercontent.com/assets/19209969/26716980/e6f43552-477b-11e7-93df-32e3c6ad96d6.png)

This is the action in Algolia:
![image](https://cloud.githubusercontent.com/assets/19209969/26717120/7e06aa92-477c-11e7-8794-cecc58e32047.png)

I don't know why reindex method removes me the index of Algolia.
Can you hel me please?
Thank you

**Comment by adampiotrowski** [comment]
@argoitz Please remove the indexes manually directly in Algolia's administration area. All needed indexes should be created during the indexation process. 

Btw. please run the reindex command using verbose mode so you can see the exception details.

`app/console wellcommerce:search:reindex -vvv`

**Comment by argoitz** [comment]
Thank you very much @adampiotrowski, the problem comes because one product has no category assigned.

The issue is fixed.
