### ISSUE TITLE
auto installer ?

### ISSUE THREAD

**Issue by ThejeswarReddy** [WellCommerce/WellCommerce#160]
hi there, make a auto installer to install the whole thing with just a click please. because i downloaded the thing but i couldn't install it with your said composer or whatever....

**Comment by adampiotrowski** [comment]
WellCommerce is an open-source software so please feel free to create such an installer on your own or whatever...

**Comment by ThejeswarReddy** [comment]
i don't know why you didn't replied but atleast provide a detailed guide on installation please...

**Comment by ThejeswarReddy** [comment]
Thanks for the reply but i thought you would make it, if i tell you on the
forum so that it helps for other users. rather than installing it manually.
