### ISSUE TITLE
Exception when trying to synchronize translations.

### ISSUE THREAD

**Issue by rmartonik** [WellCommerce/WellCommerce#38]
After making an attempt to synchronize translations, an exception is thrown:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Symfony\Bundle\FrameworkBundle\Translation\Translator' does not have a method 'getMessages'

**Comment by hacfi** [comment]
You seem to be using `WellCommerce` with Symfony 3.0 which doesn’t have that method anymore. You have to downgrade to Symfony 2.8 or below.

**Comment by adampiotrowski** [comment]
@hacfi Downgrade is not possible anymore but thanks for hint!. We'll add a fallback method to TranslationHelper.

**Comment by hacfi** [comment]
Ah ok..wasn’t aware of the upgrade. https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#user-content-translator `getMessages` is now `getCatalogue`
