### ISSUE TITLE
Problems with cart.

### ISSUE THREAD

**Issue by rmartonik** [WellCommerce/WellCommerce#40]
First scenario:
- I'm typing 1 in quantity field, then I'm clicking "Add to cart button",
- Next, I'm typing big number in quantity field (bigger than stock) and clicking "Add to cart button",
- Success message appears on the screen; quantity of this product in cart is still 1.<br/><br/>
  Second scenario:
- I'm typing big numer in quantity field
- System returns following error: ""An exception occurred while executing 'INSERT INTO cart_product (quantity, createdAt, updatedAt, cart_id, product_id, attribute_id) VALUES (?, ?, ?, ?, ?, ?)' with params [87893287498, "2016-02-18 01:57:36", "2016-02-18 01:57:36", 12, 186, null]:SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'quantity' at row 1""

**Comment by hacfi** [comment]
As you can see at https://github.com/WellCommerce/WellCommerce/blob/development/src/WellCommerce/Bundle/CartBundle/Resources/config/doctrine/CartProduct.orm.yml#L11-L13 the quantity field is mapped as integer which only allows values up to `2147483647` (see http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/types.html#integer). You have to configure the quantity limit yourself - or use bigint for that field. As with every other e-commerce software you have to configure it to your needs.

**Comment by adampiotrowski** [comment]
@hacfi You're right. What do you think of:

- setting a LessThanOrEqual in CartProduct validation

and 

- implementing an additional check (also against current product stock) here https://github.com/WellCommerce/WellCommerce/blob/development/src/WellCommerce/Bundle/CartBundle/Manager/Front/CartProductManager.php#L95-L106

I don't think that anyone will have to handle quantities greater than 1000-10000pcs.

**Comment by hacfi** [comment]
Sounds good! You can provide a sensible default like 10.000 but should be possible to configure otherwise.

**Comment by adampiotrowski** [comment]
Now i think of custom constraint as i did for UniqueUsernameValidator.(https://github.com/WellCommerce/WellCommerce/blob/development/src/WellCommerce/Bundle/ClientBundle/Doctrine/Validator/Constraints/UniqueUsernameValidator.php) or UniqueEntityValidator (https://github.com/WellCommerce/WellCommerce/blob/development/src/WellCommerce/Bundle/RoutingBundle/Doctrine/Validator/Constraints/UniqueEntityValidator.php). 

LessThanOrEqual doesn't accept constants, parameters etc. Quantity checker should be consistent in all places so custom constraint should do the job.

**Comment by adampiotrowski** [comment]
Fixed already - by using additional checks in order total visitor.
