### ISSUE TITLE
wellcommerce has a bundle about paypal?

### ISSUE THREAD

**Issue by benyang2015** [WellCommerce/WellCommerce#69]

**Comment by adampiotrowski** [comment]
@benyang2015 We're integrating Omnipay now (support for different payment gateways). Paypal processor will be available with next beta release, in about 7-10 days.

**Comment by benyang2015** [comment]
@adampiotrowski What time to release the next beta version?

**Comment by adampiotrowski** [comment]
@benyang2015 Hi, there's already a PayPal processor integrated into PaymentBundle (https://github.com/WellCommerce/WellCommerce/blob/development/src/WellCommerce/Bundle/PaymentBundle/Processor/PayPal.php) but it needs some refactorings. We plan to release next beta on Tuesday :)
