### ISSUE TITLE
User register and submit, return a 500 error

### ISSUE THREAD

**Issue by benyang2015** [WellCommerce/WellCommerce#70]

**Comment by adampiotrowski** [comment]
@benyang2015 Did you configured the mailer service through administration area (Configuration/Multistore/Shops)? Please use dev environment (app_dev.php) and paste here the exception info.

**Comment by benyang2015** [comment]
![1](https://cloud.githubusercontent.com/assets/15188607/14131339/c4e30a30-f66c-11e5-9802-7a09a424ad00.png)
Same error on the demo(http://demo.wellcommerce.org/)

**Comment by adampiotrowski** [comment]
Fixed already in previous commits & fixes.
