### ISSUE TITLE
How to create import for Wellcommerce?

### ISSUE THREAD

**Issue by folpy** [WellCommerce/WellCommerce#76]
Hi,

I need to create import of products for wellcommerce and I want to do it as a part of shop. Can you help me how to do it?

Thanks for help.

**Comment by adampiotrowski** [comment]
@folpy Hi, please give me more details. 

- What kind of file format we're talking about, XML,CSV,TXT, other?
- How big is the import? Hundreds or thousands of products? 
- Import will run on-demand ie. from administration area or it will be scheduled as a cronjob?
- Do you want to import products only or also create category trees, add producers, photos etc.?

**Comment by folpy** [comment]
- XML 
- around 5 thousands
- from administration and also via cron 
- product,producer,photo category will be created manually but I need to create pairing between category in shop and in feed

**Comment by folpy** [comment]
Do you think that it is possible to send me just a part code of something? I just need to know how to work with wellcommerce because next thing which I need is to add invoice for orders and I am not sure how to do it without working directly with wellcommerce code.

Thanks a lot for help :-)

**Comment by adampiotrowski** [comment]
@folpy Sorry for late reply. Sure, we can help you with that. We're working now on import module (only CLI version) but partially it can be implemented also in admin area. It's a matter of 2-3 days, probably next Monday.

**Comment by folpy** [comment]
Perfect I am looking forward to it. I hope that you add some tutorials very soon because that is something which currently stop my work on shop.

Thanks
