### ISSUE TITLE
Customer sign up not working

### ISSUE THREAD

**Issue by folpy** [WellCommerce/WellCommerce#77]
Hi,
I have problem with customer sign up / sign in. It doesn't work on previous beta and still doesn't work now. When I try to sign up on frontend it ends by error and I am not able to login.

**Comment by adampiotrowski** [comment]
@folpy Please paste the error message/trace here.

**Comment by folpy** [comment]
I don't know how to enable symfony debugging because I get only this error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by adampiotrowski** [comment]
Please use app_dev.php instead of app.php. If you want to enable the profiler, please verify the IP in parameters.yml in app/config, especially for Vagrant/Docker environments.

`    developer_mode.ip: 127.0.0.1`

**Comment by folpy** [comment]
Fatal error: Class 'WellCommerce\Bundle\CoreBundle\Helper\Mailer\MailerHelper' not found

**Comment by folpy** [comment]
When do you think that this bug could be solved?

**Comment by adampiotrowski** [comment]
@folpy Next beta release so in few days.
