### ISSUE TITLE
Wellcommerce Issue

### ISSUE THREAD

**Issue by Vinodkumarchoudhary** [WellCommerce/WellCommerce#83]
I face following issue after installation on windows machine through command Uncaught ::-Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: There is no extension able to load the configuration for "twig_cache" (in E:\xampp\htdocs\wellcommerce\src\WellCommerce\Bundle\AppBundle/Resources/config\app\twig.yml) line

**Comment by adampiotrowski** [comment]
@Vinodkumarchoudhary How did you install WellCommerce? Using Composer create-project command or manual from Git? Could you please check which branch is used, master or development?

**Comment by Vinodkumarchoudhary** [comment]
@adampiotrowski  i use both process:
now i use https://github.com/WellCommerce/WellCommerce these steps too.
Now i am facing following issue:-

**Comment by cdunca** [comment]
@Vinodkumarchoudhary 

Install `php_intl` module.

**Comment by Vinodkumarchoudhary** [comment]
@adampiotrowski i have already enable extension=php_intl.dll in php.ini
should i do something else for resolve this error.
Thank you

**Comment by adampiotrowski** [comment]
@Vinodkumarchoudhary Please install WellCommerce once more using Git if you want to stay up-to-date with all changes&fixes. At this moment there's no simple solution to update the application installed by using Composer create-project command. Of course you can update the dependencies (vendors) but not the root project. Installing through Git is fairly simple:

**1) clone the repository.**

git clone https://github.com/WellCommerce/WellCommerce.git path_to_wellcommerce/

I'd strongly recommend using GitHub Client if you aren't familiar with git commands.

**2) cd path_to_wellcommerce**

**3) download the Composer, install instructions https://getcomposer.org/download/**

**4) php composer.phar update**

You'll be asked for various parameters (mailer, db etc.), exactly as when you've used create-project command. 

**5) php app/console wellcommerce:install** 

This will install the database, fixtures, assets.

Then updating the WellCommerce requires only pulling changes from our repository. 

Btw. it's possible that you don't have proper PHP setup so please paste here list of installed PHP modules.

**Comment by Vinodkumarchoudhary** [comment]
i have follow all instrections and install it again again i face following issue:-
An exception has been thrown during the rendering of a template ("The Symfony\Component\Intl\NumberFormatter\NumberFormatter::__construct() method's argument $locale value '23.00' behavior is not implemented. Only the locale "en" is supported. Please install the "intl" extension for full localization capabilities.") in WellCommerceProductStatusBundle:Front\ProductStatus:products.html.twig at line 17. 

i already Install php_intl module. and enable it php.ini. 
is there any other way to resolve this issue.

**Comment by adampiotrowski** [comment]
Fixed by adding fallback currency to currency formatter
