### ISSUE TITLE
Error 500 on adding Attribute values & Attributes 

### ISSUE THREAD

**Issue by cdunca** [WellCommerce/WellCommerce#84]
On http://demo.wellcommerce.org/admin/attribute/add there is a 500 Error thrown. What I got from my local install is:

`Type error: Return value of WellCommerce\Bundle\AttributeBundle\Controller\Admin\AttributeController::getManager() must be an instance of WellCommerce\Bundle\AttributeBundle\Manager\AttributeManager, instance of WellCommerce\Bundle\DoctrineBundle\Manager\Manager returned`

Looking forward to your answear!

**Comment by razzaghi** [comment]
I fix this issue by adding this line

src/WellCommerce/Bundle/AttributeBundle/Resources/config/app/doctrine.yml


well_commerce_doctrine:
    configuration:
        attribute:
            manager: WellCommerce\Bundle\AttributeBundle\Manager\AttributeManager
            factory: WellCommerce\Bundle\AttributeBundle\Factory\AttributeFactory

**manager: WellCommerce\Bundle\AttributeBundle\Manager\AttributeManager**

but other problem is exist yet

**Comment by adampiotrowski** [comment]
Fixed
