### ISSUE TITLE
GFormDistinctionEditor is not define`

### ISSUE THREAD

**Issue by razzaghi** [WellCommerce/WellCommerce#85]
when i  call add product route i get GFormDistinctionEditor is not define.
what is the problem please help me

**Comment by adampiotrowski** [comment]
@razzaghi Which branch and tag are you using now?

**Comment by razzaghi** [comment]
Development
Product page show blank
Even in demo on admin add product show as blank page

**Comment by adampiotrowski** [comment]
@razzaghi You can fix it locally by compiling JS assets using Gulp. Run two commands in project's root.

```
npm install
gulp
```
you should see something like this
```
[22:22:57] Using gulpfile ~/Sites/WellCommerce/Gulpfile.js
[22:22:57] Starting 'admin-libs'...
[22:22:57] Starting 'admin-core'...
[22:22:57] Starting 'admin-css'...
[22:22:57] Starting 'admin-images'...
[22:22:58] Finished 'admin-core' after 770 ms
[22:22:58] Finished 'admin-css' after 837 ms
[22:23:08] Finished 'admin-libs' after 10 s
[22:23:08] Finished 'admin-images' after 10 s
[22:23:08] Starting 'default'...
[22:23:08] Finished 'default' after 20 μs
```

Otherwise please wait few days. We're still preparing a huge beta release.

**Comment by razzaghi** [comment]
when i run these commands every thing gone
any pages don't show true every things is blank and got error in console

libs.js:1 Uncaught ReferenceError: Translator is not defined(anonymous function) @ libs.js:1
routing?callback=fos.Router.setData:1 Uncaught ReferenceError: fos is not defined(anonymous function) @ routing?callback=fos.Router.setData:1
index:13 Uncaught ReferenceError: GCore is not defined(anonymous function) @ index:13
core.js:3 Uncaught ReferenceError: GCore is not defined(anonymous function) @ core.js:3
index:31 Uncaught ReferenceError: $ is not defined(anonymous function) @ index:31
index:310 Uncaught ReferenceError: $ is not defined(anonymous function) @ index:310

**Comment by adampiotrowski** [comment]
@razzaghi try re-installing the symfony assets

```
assets:install --symlink --relative
bazinga:js-translation:dump
fos:js-routing:dump
```

**Comment by razzaghi** [comment]
doesn't work these command

**Comment by adampiotrowski** [comment]
@razzaghi 
try
```
php app/console assets:install --symlink --relative
php app/console bazinga:js-translation:dump
php app/console fos:js-routing:dump
```

**Comment by razzaghi** [comment]
i know i run these commands but doesn't solve my problem
