### ISSUE TITLE
enable multi language in site?

### ISSUE THREAD

**Issue by razzaghi** [WellCommerce/WellCommerce#88]
How can i enable multi language in site frontend?

**Comment by adampiotrowski** [comment]
@razzaghi 

Use console command to add a new language/locale

```
app/console wellcommerce:locale:add
```
You'll be asked about target, source locale and default currency. It will create a copy of source locale.

In next beta all static translations will be translatable through admin area, at this moment the dictionary syncing process doesn't work :(. You can overcome this issue by adding the translation files in app/Resources/translations/wellcommerce.{LOCALE_CODE}.yml

**Comment by razzaghi** [comment]
I add new locale before but it is not enable in frontend and can't switch to it

**Comment by adampiotrowski** [comment]
You must edit the added locale and check the "Locale will be visible in shop" option.
