### ISSUE TITLE
add media problem

### ISSUE THREAD

**Issue by razzaghi** [WellCommerce/WellCommerce#89]
when i want to add media i got this error

Type error: Argument 1 passed to WellCommerce\Bundle\MediaBundle\Uploader\MediaUploader::upload() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given, called in \WellCommerce\src\WellCommerce\Bundle\MediaBundle\Controller\Admin\MediaController.php on line 39

**Comment by adampiotrowski** [comment]
@razzaghi Please check if the issue still exists after updating to newest version.

**Comment by argoitz** [comment]
Hi @adampiotrowski, i update repository to the last version and I still exist this issue. 
How can we solve it?
Thank you.

**Comment by adampiotrowski** [comment]
Fixed with #121
