### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by razzaghi** [WellCommerce/WellCommerce#95]
when i add an sentence to search got this error

Type error: Argument 2 passed to WellCommerce\Bundle\CoreBundle\DataSet\AbstractDataSet::__construct() must implement interface WellCommerce\Component\DataSet\Manager\DataSetManagerInterface, none given, called in D:\Projects\Ferdosi\Ferdosicom\app\cache\dev\appDevDebugProjectContainer.php on line 11281

**Comment by razzaghi** [comment]
do you see this problem? can you help me to solve it?

**Comment by adampiotrowski** [comment]
@razzaghi Fixed on development branch.
