### ISSUE TITLE
getting error when i want to add new locale

### ISSUE THREAD

**Issue by razzaghi** [WellCommerce/WellCommerce#97]
in this version after pulling today commits i got below error for add new locale

[Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException]
  Neither the property "shortDescription" nor one of the methods "getShortDescription()", "shortDescription()", "isSh
  ortDescription()", "hasShortDescription()", "__get()" exist and have public access in class "WellCommerce\Bundle\At
  tributeBundle\Entity\AttributeTranslation".

**Comment by adampiotrowski** [comment]
@razzaghi I pushed a small fix, please update and let me know if it helps.

**Comment by razzaghi** [comment]
It is okay thanks a lot
