### ISSUE TITLE
Add product error

### ISSUE THREAD

**Issue by razzaghi** [WellCommerce/WellCommerce#99]
when we want to add product get error please check it

**Comment by adampiotrowski** [comment]
Please describe the error. Do you have any error trace?

**Comment by razzaghi** [comment]
I got this error
Type error: Return value of WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation::getRoute() must implement interface WellCommerce\Bundle\RoutingBundle\Entity\RouteInterface, null returned

**Comment by razzaghi** [comment]
adam can u help for this problem?

**Comment by adampiotrowski** [comment]
Fixed in latest commits.
